# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Asterius' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Asterius

  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'


  pod 'RNIap', :path => '../node_modules/react-native-iap'

  pod 'react-native-in-app-utils', :path => '../node_modules/react-native-in-app-utils'

  target 'AsteriusTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Asterius-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Asterius-tvOS

  target 'Asterius-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
